# Generated by Django 5.2.4 on 2026-04-20 20:02

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('last_price_yes', models.DecimalField(decimal_places=4, default=Decimal('0.5000'), max_digits=6)),
                ('fee_bps', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='SimulationAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('starting_balance', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=14)),
                ('balance_cash', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=14)),
                ('balance_reserved', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('fee_rate', models.DecimalField(decimal_places=5, default=Decimal('0.01000'), max_digits=6)),
                ('position_limit', models.DecimalField(decimal_places=2, default=Decimal('250.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorldSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('rss', 'RSS'), ('social', 'Social'), ('news_api', 'News API')], max_length=20)),
                ('source_name', models.CharField(max_length=120)),
                ('headline', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sentiment_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('impact_score', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('entry_prob', models.DecimalField(decimal_places=4, max_digits=6)),
                ('close_prob', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('size_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity_shares', models.DecimalField(decimal_places=6, max_digits=14)),
                ('fee_open', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('fee_close', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('pnl_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='simulator.market')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='simulator.simulationaccount')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('buy', 'BUY'), ('sell', 'SELL')], max_length=10)),
                ('side', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=10)),
                ('probability', models.DecimalField(decimal_places=4, max_digits=6)),
                ('size_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('expected_edge', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='simulator.simulationaccount')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='simulator.market')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='simulator.position')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('probability_yes', models.DecimalField(decimal_places=4, max_digits=6)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reasoning', models.TextField(blank=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='simulator.market')),
                ('signals', models.ManyToManyField(blank=True, related_name='predictions', to='simulator.worldsignal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(default=django.utils.timezone.localdate)),
                ('equity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=14)),
                ('open_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('closed_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('trade_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='simulator.simulationaccount')),
            ],
            options={
                'ordering': ['-snapshot_date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('account', 'snapshot_date'), name='uniq_account_snapshot_date')],
            },
        ),
    ]
