# Generated by Django 5.2.4 on 2026-04-20 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_market_external_id_market_liquidity_usd_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='performancesnapshot',
            name='uniq_account_snapshot_date',
        ),
    ]
