# Generated by Django 5.2.4 on 2026-04-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0004_marketpricetick'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='clob_token_id',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
