upstream gunicorn_trading {
    server 127.0.0.1:8008;
}

# HTTP (before SSL certificate is obtained)
server {
    listen 80;
    server_name trading.hs-dev.cz;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location /static/ {
        alias /srv/apps/08_trading/staticfiles/;
    }

    location / {
        include proxy_params;
        proxy_pass http://gunicorn_trading;
    }
}
